// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    island: {
      landwidth: 12,
      landheight: 12
    },
    html: {
      imagedir: "/images/"
    },
    unit: {
      population: "00人",
      tree: "00本"
    },
    base: {
      hide: true
    }
  };

}).call(this);
